-- luacheck: globals RP
---@diagnostic disable: undefined-global
-- Arquivo organizado automaticamente (sem alterar dados).
local AddonEmotes = {
  AnimalEmotes = {
  },
  Dances = {
  },
  Emotes = {
  },
  Exits = {
  },
  Expressions = {
  },
  PropEmotes = {
  },
  Shared = {
    wc_carrya1 = {
      "wc_carrya1@animations",
      "pcarrya1clip",
      "~r~New ~p~Monaco 1 Shoulder Covering Eyes",
      "wc_carrya2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carrya2 = {
      "wc_carrya2@animations",
      "pcarrya2clip",
      "~r~New ~p~Monaco 2 Shoulder Covering Eyes",
      "wc_carrya1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryb1 = {
      "wc_carryb1@animations",
      "pcarryb1clip",
      "~r~New ~p~Monaco 1 Struggle Behind",
      "wc_carryb2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryb2 = {
      "wc_carryb2@animations",
      "pcarryb2clip",
      "~r~New ~p~Monaco 2 Struggle Behind",
      "wc_carryb1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryc1 = {
      "wc_carryc1@animations",
      "pcarryc1clip",
      "~r~New ~p~Monaco 1 Dead Behind",
      "wc_carryc2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryc2 = {
      "wc_carryc2@animations",
      "pcarryc2clip",
      "~r~New ~p~Monaco 2 Dead Behind",
      "wc_carryc1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.36,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -10.0,
      },
    },
    wc_carryd1 = {
      "wc_carryd1@animations",
      "pcarryd1clip",
      "~r~New ~p~Monaco 1 Firemans Shoulder",
      "wc_carryd2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryd2 = {
      "wc_carryd2@animations",
      "pcarryd2clip",
      "~r~New ~p~Monaco 2 Firemans Shoulder",
      "wc_carryd1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.12,
        xRot = 0.0,
        yPos = -0.15,
        yRot = 0.0,
        zPos = -0.05,
        zRot = -3.0,
      },
    },
    wc_carrye1 = {
      "wc_carrye1@animations",
      "pcarrye1clip",
      "~r~New ~p~Monaco 1 Standing Shoulder",
      "wc_carrye2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carrye2 = {
      "wc_carrye2@animations",
      "pcarrye2clip",
      "~r~New ~p~Monaco 2 Standing Shoulder",
      "wc_carrye1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.23,
        xRot = 0.0,
        yPos = 0.02,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryf1 = {
      "wc_carryf1@animations",
      "pcarryf1clip",
      "~r~New ~p~Monaco 1 Meditation Feet On Head",
      "wc_carryf2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryf2 = {
      "wc_carryf2@animations",
      "pcarryf2clip",
      "~r~New ~p~Monaco 2 Meditation Feet On Head",
      "wc_carryf1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.23,
        xRot = 0.0,
        yPos = 0.02,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryg1 = {
      "wc_carryg1@animations",
      "pcarryg1clip",
      "~r~New ~p~Monaco 1 Superman",
      "wc_carryg2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryg2 = {
      "wc_carryg2@animations",
      "pcarryg2clip",
      "~r~New ~p~Monaco 2 Superman",
      "wc_carryg1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.85,
        xRot = 0.0,
        yPos = -0.12,
        yRot = 0.0,
        zPos = -0.02,
        zRot = 0.0,
      },
    },
    wc_carryh1 = {
      "wc_carryh1@animations",
      "pcarryh1clip",
      "~r~New ~p~Monaco 1 Cute Shoulder Back",
      "wc_carryh2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryh2 = {
      "wc_carryh2@animations",
      "pcarryh2clip",
      "~r~New ~p~Monaco 2 Cute Shoulder Back",
      "wc_carryh1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.13,
        xRot = 0.0,
        yPos = -0.13,
        yRot = 0.0,
        zPos = -0.05,
        zRot = 0.0,
      },
    },
    wc_carryi1 = {
      "wc_carryi1@animations",
      "pcarryi1clip",
      "~r~New ~p~Monaco 1 Bird",
      "wc_carryi2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryi2 = {
      "wc_carryi2@animations",
      "pcarryi2clip",
      "~r~New ~p~Monaco 2 Bird",
      "wc_carryi1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.7,
        xRot = 0.0,
        yPos = -0.33,
        yRot = 0.0,
        zPos = 0.0,
        zRot = -15.0,
      },
    },
    wc_carryj1 = {
      "wc_carryj1@animations",
      "pcarryj1clip",
      "~r~New ~p~Monaco 1 Woohoo",
      "wc_carryj2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryj2 = {
      "wc_carryj2@animations",
      "pcarryj2clip",
      "~r~New ~p~Monaco 2 Woohoo",
      "wc_carryj1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.35,
        xRot = 0.0,
        yPos = -0.49,
        yRot = 0.0,
        zPos = 0.0,
        zRot = -30.0,
      },
    },
    wc_carryk1 = {
      "wc_carryk1@animations",
      "pcarryk1clip",
      "~r~New ~p~Monaco 1 Sad Curl Up",
      "wc_carryk2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryk2 = {
      "wc_carryk2@animations",
      "pcarryk2clip",
      "~r~New ~p~Monaco 2 Sad Curl Up",
      "wc_carryk1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.06,
        xRot = 0.0,
        yPos = 0.1,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryl1 = {
      "wc_carryl1@animations",
      "pcarryl1clip",
      "~r~New ~p~Monaco 1 Sad Front",
      "wc_carryl2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryl2 = {
      "wc_carryl2@animations",
      "pcarryl2clip",
      "~r~New ~p~Monaco 2 Sad Front",
      "wc_carryl1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.05,
        xRot = 0.0,
        yPos = 0.07,
        yRot = 0.0,
        zPos = 0.02,
        zRot = 0.0,
      },
    },
    wc_carrym1 = {
      "wc_carrym1@animations",
      "pcarrym1clip",
      "~r~New ~p~Monaco 1 Standing Upside Down",
      "wc_carrym2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carrym2 = {
      "wc_carrym2@animations",
      "pcarrym2clip",
      "~r~New ~p~Monaco 2 Standing Upside Down",
      "wc_carrym1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.82,
        xRot = 0.0,
        yPos = 0.15,
        yRot = 0.0,
        zPos = -0.02,
        zRot = 5.0,
      },
    },
    wc_carryn1 = {
      "wc_carryn1@animations",
      "pcarryn1clip",
      "~r~New ~p~Monaco 1 Salute",
      "wc_carryn2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryn2 = {
      "wc_carryn2@animations",
      "pcarryn2clip",
      "~r~New ~p~Monaco 2 Salute",
      "wc_carryn1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.23,
        xRot = 0.0,
        yPos = 0.02,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryo1 = {
      "wc_carryo1@animations",
      "pcarryo1clip",
      "~r~New ~p~Monaco 1 Arrogant",
      "wc_carryo2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryo2 = {
      "wc_carryo2@animations",
      "pcarryo2clip",
      "~r~New ~p~Monaco 2 Arrogant",
      "wc_carryo1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.55,
        xRot = 0.0,
        yPos = 0.01,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryp1 = {
      "wc_carryp1@animations",
      "pcarryp1clip",
      "~r~New ~p~Monaco 1 Dab",
      "wc_carryp2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryp2 = {
      "wc_carryp2@animations",
      "pcarryp2clip",
      "~r~New ~p~Monaco 2 Dab",
      "wc_carryp1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.55,
        xRot = 0.0,
        yPos = 0.01,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryq1 = {
      "wc_carryq1@animations",
      "pcarryq1clip",
      "~r~New ~p~Monaco 1 Bull Meditation",
      "wc_carryq2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryq2 = {
      "wc_carryq2@animations",
      "pcarryq2clip",
      "~r~New ~p~Monaco 2 Bull Meditation",
      "wc_carryq1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.2,
        xRot = 0.0,
        yPos = -0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = -80.0,
      },
    },
    wc_carryr1 = {
      "wc_carryr1@animations",
      "pcarryr1clip",
      "~r~New ~p~Monaco 1 Cute Shy Shoulder",
      "wc_carryr2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryr2 = {
      "wc_carryr2@animations",
      "pcarryr2clip",
      "~r~New ~p~Monaco 2 Cute Shy Shoulder",
      "wc_carryr1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.07,
        xRot = 0.0,
        yPos = -0.1,
        yRot = 0.0,
        zPos = -0.28,
        zRot = 0.0,
      },
    },
    wc_carrys1 = {
      "wc_carrys1@animations",
      "pcarrys1clip",
      "~r~New ~p~Monaco 2 Sleep Over Head",
      "wc_carrys2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carrys2 = {
      "wc_carrys2@animations",
      "pcarrys2clip",
      "~r~New ~p~Monaco 2 Sleep Over Head",
      "wc_carrys1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.88,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = -0.08,
        zRot = 0.0,
      },
    },
    wc_carryt1 = {
      "wc_carryt1@animations",
      "pcarryt1clip",
      "~r~New ~p~Monaco 1 Riding Motorcycle",
      "wc_carryt2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryt2 = {
      "wc_carryt2@animations",
      "pcarryt2clip",
      "~r~New ~p~Monaco 2 Riding Motorcycle",
      "wc_carryt1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.52,
        xRot = 0.0,
        yPos = 0.03,
        yRot = 0.0,
        zPos = -0.01,
        zRot = 0.0,
      },
    },
    wc_carryu1 = {
      "wc_carryu1@animations",
      "pcarryu1clip",
      "~r~New ~p~Monaco 1 Cute Sit Shoulder",
      "wc_carryu2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryu2 = {
      "wc_carryu2@animations",
      "pcarryu2clip",
      "~r~New ~p~Monaco 2 Cute Sit Shoulder",
      "wc_carryu1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.29,
        xRot = 0.0,
        yPos = 0.04,
        yRot = 0.0,
        zPos = -0.22,
        zRot = 0.0,
      },
    },
    wc_carryv1 = {
      "wc_carryv1@animations",
      "pcarryv1clip",
      "~r~New ~p~Monaco 1 Pull Head Back",
      "wc_carryv2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryv2 = {
      "wc_carryv2@animations",
      "pcarryv2clip",
      "~r~New ~p~Monaco 2 Pull Head Back",
      "wc_carryv1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.34,
        xRot = 0.0,
        yPos = -0.18,
        yRot = 0.0,
        zPos = 0.15,
        zRot = 50.0,
      },
    },
    wc_carryw1 = {
      "wc_carryw1@animations",
      "pcarryw1clip",
      "~r~New ~p~Monaco 1 Disgusting",
      "wc_carryw2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryw2 = {
      "wc_carryw2@animations",
      "pcarryw2clip",
      "~r~New ~p~Monaco 2 Disgusting",
      "wc_carryw1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 28422,
        xPos = 0.0,
        xRot = 0.0,
        yPos = -0.14,
        yRot = 0.0,
        zPos = -0.41,
        zRot = 0.0,
      },
    },
    wc_carryx1 = {
      "wc_carryx1@animations",
      "pcarryx1clip",
      "~r~New ~p~Monaco 1 Caught",
      "wc_carryx2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryx2 = {
      "wc_carryx2@animations",
      "pcarryx2clip",
      "~r~New ~p~Monaco 2 Caught",
      "wc_carryx1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 28422,
        xPos = 0.25,
        xRot = 0.0,
        yPos = -0.2,
        yRot = 0.0,
        zPos = 0.13,
        zRot = 0.0,
      },
    },
    wc_carryy1 = {
      "wc_carryy1@animations",
      "pcarryy1clip",
      "~r~New ~p~Monaco 1 Torture",
      "wc_carryy2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryy2 = {
      "wc_carryy2@animations",
      "pcarryy2clip",
      "~r~New ~p~Monaco 2 Torture",
      "wc_carryy1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 28422,
        xPos = 0.24,
        xRot = 0.0,
        yPos = -0.56,
        yRot = 0.0,
        zPos = 0.75,
        zRot = -160.0,
      },
    },
    wc_carryz1 = {
      "wc_carryz1@animations",
      "pcarryz1clip",
      "~r~New ~p~Monaco 1 Bazoka",
      "wc_carryz2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryz2 = {
      "wc_carryz2@animations",
      "pcarryz2clip",
      "~r~New ~p~Monaco 2 Bazoka",
      "wc_carryz1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 57005,
        xPos = 0.02,
        xRot = 0.0,
        yPos = 0.19,
        yRot = 0.0,
        zPos = -0.22,
        zRot = -79.999,
      },
    },
    wc_carryza1 = {
      "wc_carryza1@animations",
      "pcarryza1clip",
      "~r~New ~p~Monaco 1 Drunk Behind",
      "wc_carryza2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryza2 = {
      "wc_carryza2@animations",
      "pcarryza2clip",
      "~r~New ~p~Monaco 2 Drunk Behind",
      "wc_carryza1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.56,
        xRot = 0.0,
        yPos = 0.03,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryzb1 = {
      "wc_carryzb1@animations",
      "pcarryzb1clip",
      "~r~New ~p~Monaco 1 Peek High",
      "wc_carryzb2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzb2 = {
      "wc_carryzb2@animations",
      "pcarryzb2clip",
      "~r~New ~p~Monaco 2 Peek High",
      "wc_carryzb1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.943,
        xRot = 0.0,
        yPos = -0.01,
        yRot = 0.0,
        zPos = -0.024,
        zRot = 0.0,
      },
    },
    wc_carryzc1 = {
      "wc_carryzc1@animations",
      "pcarryzc1clip",
      "~r~New ~p~Monaco 1 Meditation Master",
      "wc_carryzc2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzc2 = {
      "wc_carryzc2@animations",
      "pcarryzc2clip",
      "~r~New ~p~Monaco 2 Meditation Master",
      "wc_carryzc1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.16,
        xRot = 0.0,
        yPos = 0.02,
        yRot = 0.0,
        zPos = -0.02,
        zRot = 0.0,
      },
    },
    wc_carryzd1 = {
      "wc_carryzd1@animations",
      "pcarryzd1clip",
      "~r~New ~p~Monaco 1 Strongman",
      "wc_carryzd2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzd2 = {
      "wc_carryzd2@animations",
      "pcarryzd2clip",
      "~r~New ~p~Monaco 2 Strongman",
      "wc_carryzd1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.59,
        xRot = 0.0,
        yPos = 0.01,
        yRot = 0.0,
        zPos = -0.02,
        zRot = 0.0,
      },
    },
    wc_carryze1 = {
      "wc_carryze1@animations",
      "pcarryze1clip",
      "~r~New ~p~Monaco 1 Cute Piggyback",
      "wc_carryze2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryze2 = {
      "wc_carryze2@animations",
      "pcarryze2clip",
      "~r~New ~p~Monaco 2 Cute Piggyback",
      "wc_carryze1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.18,
        xRot = 0.0,
        yPos = -0.02,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -10.0,
      },
    },
    wc_carryzf1 = {
      "wc_carryzf1@animations",
      "pcarryzf1clip",
      "~r~New ~p~Monaco 1 Piggyback Run",
      "wc_carryzf2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzf2 = {
      "wc_carryzf2@animations",
      "pcarryzf2clip",
      "~r~New ~p~Monaco 2 Piggyback Run",
      "wc_carryzf1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.21,
        xRot = 0.0,
        yPos = -0.27,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -90.0,
      },
    },
    wc_carryzg1 = {
      "wc_carryzg1@animations",
      "pcarryzg1clip",
      "~r~New ~p~Monaco 1 Pulling Hands Back",
      "wc_carryzg2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzg2 = {
      "wc_carryzg2@animations",
      "pcarryzg2clip",
      "~r~New ~p~Monaco 2 Pulling Hands Back",
      "wc_carryzg1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.15,
        xRot = 0.0,
        yPos = -0.67,
        yRot = 0.0,
        zPos = -0.01,
        zRot = -80.0,
      },
    },
    wc_carryzh1 = {
      "wc_carryzh1@animations",
      "pcarryzh1clip",
      "~r~New ~p~Monaco 1 Pole",
      "wc_carryzh2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzh2 = {
      "wc_carryzh2@animations",
      "pcarryzh2clip",
      "~r~New ~p~Monaco 2 Pole",
      "wc_carryzh1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.11,
        xRot = 0.0,
        yPos = 0.12,
        yRot = 0.0,
        zPos = -0.27,
        zRot = -10.0,
      },
    },
    wc_carryzi1 = {
      "wc_carryzi1@animations",
      "pcarryzi1clip",
      "~r~New ~p~Monaco 1 Cute Front",
      "wc_carryzi2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzi2 = {
      "wc_carryzi2@animations",
      "pcarryzi2clip",
      "~r~New ~p~Monaco 2 Cute Front",
      "wc_carryzi1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.1,
        xRot = 0.0,
        yPos = 0.25,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_carryzj1 = {
      "wc_carryzj1@animations",
      "pcarryzj1clip",
      "~r~New ~p~Monaco 1 Caress Head",
      "wc_carryzj2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzj2 = {
      "wc_carryzj2@animations",
      "pcarryzj2clip",
      "~r~New ~p~Monaco 2 Caress Head",
      "wc_carryzj1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.27,
        xRot = 0.0,
        yPos = 0.01,
        yRot = 0.0,
        zPos = -0.06,
        zRot = 0.0,
      },
    },
    wc_carryzk1 = {
      "wc_carryzk1@animations",
      "pcarryzk1clip",
      "~r~New ~p~Monaco 1 Cute Scared",
      "wc_carryzk2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzk2 = {
      "wc_carryzk2@animations",
      "pcarryzk2clip",
      "~r~New ~p~Monaco 2 Cute Scared",
      "wc_carryzk1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.2,
        xRot = 0.0,
        yPos = 0.01,
        yRot = 0.0,
        zPos = 0.1,
        zRot = 0.0,
      },
    },
    wc_carryzl1 = {
      "wc_carryzl1@animations",
      "pcarryzl1clip",
      "~r~New ~p~Monaco 1 Bag",
      "wc_carryzl2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzl2 = {
      "wc_carryzl2@animations",
      "pcarryzl2clip",
      "~r~New ~p~Monaco 2 Bag",
      "wc_carryzl1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.04,
        xRot = 0.0,
        yPos = 0.06,
        yRot = 0.0,
        zPos = -0.03,
        zRot = 0.0,
      },
    },
    wc_carryzm1 = {
      "wc_carryzm1@animations",
      "pcarryzm1clip",
      "~r~New ~p~Monaco 1 Bag Flip",
      "wc_carryzm2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzm2 = {
      "wc_carryzm2@animations",
      "pcarryzm2clip",
      "~r~New ~p~Monaco 2 Bag Flip",
      "wc_carryzm1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.12,
        xRot = 0.0,
        yPos = 0.05,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -15.0,
      },
    },
    wc_carryzn1 = {
      "wc_carryzn1@animations",
      "pcarryzn1clip",
      "~r~New ~p~Monaco 1 Hug Back Flip",
      "wc_carryzn2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzn2 = {
      "wc_carryzn2@animations",
      "pcarryzn2clip",
      "~r~New ~p~Monaco 2 Hug Back Flip",
      "wc_carryzn1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.21,
        xRot = 0.0,
        yPos = 0.05,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -15.0,
      },
    },
    wc_carryzo1 = {
      "wc_carryzo1@animations",
      "pcarryzo1clip",
      "~r~New ~p~Monaco 1 Sit & Wave Over Head",
      "wc_carryzo2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzo2 = {
      "wc_carryzo2@animations",
      "pcarryzo2clip",
      "~r~New ~p~Monaco 2 Sit & Wave Over Head",
      "wc_carryzo1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.19,
        xRot = 0.0,
        yPos = -0.02,
        yRot = 0.0,
        zPos = -0.02,
        zRot = 0.0,
      },
    },
    wc_carryzp1 = {
      "wc_carryzp1@animations",
      "pcarryzp1clip",
      "~r~New ~p~Monaco 1 Cute Punch Head",
      "wc_carryzp2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzp2 = {
      "wc_carryzp2@animations",
      "pcarryzp2clip",
      "~r~New ~p~Monaco 2 Cute Punch Head",
      "wc_carryzp1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.45,
        xRot = 0.0,
        yPos = -0.16,
        yRot = 0.0,
        zPos = -0.03,
        zRot = 0.0,
      },
    },
    wc_carryzq1 = {
      "wc_carryzq1@animations",
      "pcarryzq1clip",
      "~r~New ~p~Monaco 1 Superhero",
      "wc_carryzq2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzq2 = {
      "wc_carryzq2@animations",
      "pcarryzq2clip",
      "~r~New ~p~Monaco 2 Superhero",
      "wc_carryzq1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.27,
        xRot = 0.0,
        yPos = 0.54,
        yRot = 0.0,
        zPos = -0.02,
        zRot = 0.0,
      },
    },
    wc_carryzr1 = {
      "wc_carryzr1@animations",
      "pcarryzr1clip",
      "~r~New ~p~Monaco 1 Shoulder Leg Cross Head",
      "wc_carryzr2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzr2 = {
      "wc_carryzr2@animations",
      "pcarryzr2clip",
      "~r~New ~p~Monaco 2 Shoulder Leg Cross Head",
      "wc_carryzr1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.6,
        xRot = 0.0,
        yPos = -0.09,
        yRot = 0.0,
        zPos = 0.02,
        zRot = 0.0,
      },
    },
    wc_carryzs1 = {
      "wc_carryzs1@animations",
      "pcarryzs1clip",
      "~r~New ~p~Monaco 1 Can't Breath",
      "wc_carryzs2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzs2 = {
      "wc_carryzs2@animations",
      "pcarryzs2clip",
      "~r~New ~p~Monaco 2 Can't Breath",
      "wc_carryzs1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.03,
        xRot = 0.0,
        yPos = -0.18,
        yRot = 0.0,
        zPos = 0.02,
        zRot = 0.0,
      },
    },
    wc_carryzt1 = {
      "wc_carryzt1@animations",
      "pcarryzt1clip",
      "~r~New ~p~Monaco 1 Firemans Back",
      "wc_carryzt2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzt2 = {
      "wc_carryzt2@animations",
      "pcarryzt2clip",
      "~r~New ~p~Monaco 2 Firemans Back",
      "wc_carryzt1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.33,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = -0.04,
        zRot = -80.0,
      },
    },
    wc_carryzu1 = {
      "wc_carryzu1@animations",
      "pcarryzu1clip",
      "~r~New ~p~Monaco 1 Happy Behind",
      "wc_carryzu2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzu2 = {
      "wc_carryzu2@animations",
      "pcarryzu2clip",
      "~r~New ~p~Monaco 2 Happy Behind",
      "wc_carryzu1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.29,
        xRot = 0.0,
        yPos = -0.3,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -80.0,
      },
    },
    wc_carryzv1 = {
      "wc_carryzv1@animations",
      "pcarryzv1clip",
      "~r~New ~p~Monaco 1 Happy Swing",
      "wc_carryzv2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzv2 = {
      "wc_carryzv2@animations",
      "pcarryzv2clip",
      "~r~New ~p~Monaco 2 Happy Swing",
      "wc_carryzv1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = -0.04,
        xRot = 0.0,
        yPos = -0.72,
        yRot = 0.0,
        zPos = -0.6,
        zRot = 0.0,
      },
    },
    wc_carryzw1 = {
      "wc_carryzw1@animations",
      "pcarryzw1clip",
      "~r~New ~p~Monaco 1 Piggyback Head",
      "wc_carryzw2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzw2 = {
      "wc_carryzw2@animations",
      "pcarryzw2clip",
      "~r~New ~p~Monaco 2 Piggyback Head",
      "wc_carryzw1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.32,
        xRot = 0.0,
        yPos = -0.22,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -80.0,
      },
    },
    wc_carryzx1 = {
      "wc_carryzx1@animations",
      "pcarryzx1clip",
      "~r~New ~p~Monaco 1 Pose Over Head",
      "wc_carryzx2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzx2 = {
      "wc_carryzx2@animations",
      "pcarryzx2clip",
      "~r~New ~p~Monaco 2 Pose Over Head",
      "wc_carryzx1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.43,
        xRot = 0.0,
        yPos = -0.86,
        yRot = 0.0,
        zPos = 0.0,
        zRot = -80.0,
      },
    },
    wc_carryzy1 = {
      "wc_carryzy1@animations",
      "pcarryzy1clip",
      "~r~New ~p~Monaco 1 Piggyback Hold Head",
      "wc_carryzy2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzy2 = {
      "wc_carryzy2@animations",
      "pcarryzy2clip",
      "~r~New ~p~Monaco 2 Piggyback Hold Head",
      "wc_carryzy1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 0.06,
        xRot = 0.0,
        yPos = -0.07,
        yRot = 0.0,
        zPos = -0.02,
        zRot = -20.0,
      },
    },
    wc_carryzz1 = {
      "wc_carryzz1@animations",
      "pcarryzz1clip",
      "~r~New ~p~Monaco 1 Heart Power",
      "wc_carryzz2",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = true,
      },
    },
    wc_carryzz2 = {
      "wc_carryzz2@animations",
      "pcarryzz2clip",
      "~r~New ~p~Monaco 2 Heart Power",
      "wc_carryzz1",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        bone = 24818,
        xPos = 1.11,
        xRot = 0.0,
        yPos = 0.21,
        yRot = 0.0,
        zPos = -0.78,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_01a = {
      "whitecustom@ccustomv1",
      "pandora01",
      "~r~New ~b~Monaco Ind 1 (1)",
      "wc_ccustomv1_01b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_01b = {
      "whitecustom@ccustomv1",
      "pandora01",
      "~r~New ~b~Monaco Ind 1 (2)",
      "wc_ccustomv1_01a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_ccustomv1_02a = {
      "whitecustom@ccustomv1",
      "pandora02",
      "~r~New ~b~Monaco Ind 2 (1)",
      "wc_ccustomv1_02b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_02b = {
      "whitecustom@ccustomv1",
      "pandora02",
      "~r~New ~b~Monaco Ind 2 (2)",
      "wc_ccustomv1_02a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_ccustomv1_03a = {
      "whitecustom@ccustomv1",
      "pandora03",
      "~r~New ~b~Monaco Ind 3 (1)",
      "wc_ccustomv1_03b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_03b = {
      "whitecustom@ccustomv1",
      "pandora03",
      "~r~New ~b~Monaco Ind 3 (2)",
      "wc_ccustomv1_03a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_ccustomv1_04a = {
      "whitecustom@ccustomv1",
      "pandora04",
      "~r~New ~b~Monaco Ind 4 (1)",
      "wc_ccustomv1_04b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_04b = {
      "whitecustom@ccustomv1",
      "pandora04",
      "~r~New ~b~Monaco Ind 4 (2)",
      "wc_ccustomv1_04a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_ccustomv1_05a = {
      "whitecustom@ccustomv1",
      "pandora05",
      "~r~New ~b~Monaco Ind 5 (1)",
      "wc_ccustomv1_05b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_05b = {
      "whitecustom@ccustomv1",
      "pandora05",
      "~r~New ~b~Monaco Ind 5 (2)",
      "wc_ccustomv1_05a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_ccustomv1_06a = {
      "whitecustom@ccustomv1",
      "pandora06",
      "~r~New ~b~Monaco Ind 6 (1)",
      "wc_ccustomv1_06b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_ccustomv1_06b = {
      "whitecustom@ccustomv1",
      "pandora06",
      "~r~New ~b~Monaco Ind 6 (2)",
      "wc_ccustomv1_06a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_chill1s = {
      "whitecustom@chill",
      "pandora_fem",
      "~r~New ~b~Monaco Chill 1 (F)",
      "wc_chill2s",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_chill2s = {
      "whitecustom@chill",
      "pandora_male",
      "~r~New ~b~Monaco Chill 1 (M)",
      "wc_chill1s",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_chill6_s1 = {
      "whitecustom@chill6",
      "pandora",
      "~r~New ~b~Monaco Chill 6 (F)",
      "wc_chill6_s2",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_chill6_s2 = {
      "whitecustom@chill7",
      "pandora",
      "~r~New ~b~Monaco Chill 7 (M)",
      "wc_chill6_s1",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_fuckitup01a = {
      "whitecustom@fckitup-1",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 1 (1)",
      "wc_fuckitup01b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_fuckitup01b = {
      "whitecustom@fckitup-1",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 1 (2)",
      "wc_fuckitup01a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_fuckitup02a = {
      "whitecustom@fckitup-2",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 2 (1)",
      "wc_fuckitup02b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_fuckitup02b = {
      "whitecustom@fckitup-2",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 2 (2)",
      "wc_fuckitup02a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_fuckitup03a = {
      "whitecustom@fckitup-3",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 3 (1)",
      "wc_fuckitup03b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_fuckitup03b = {
      "whitecustom@fckitup-3",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 3 (2)",
      "wc_fuckitup03a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_fuckitup04a = {
      "whitecustom@fckitup-4",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 4 (1)",
      "wc_fuckitup04b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_fuckitup04b = {
      "whitecustom@fckitup-4",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 4 (2)",
      "wc_fuckitup04a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_fuckitup05a = {
      "whitecustom@fckitup-5",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 5 (1)",
      "wc_fuckitup05b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_fuckitup05b = {
      "whitecustom@fckitup-5",
      "pandora",
      "~r~New ~b~Monaco F*ck It Up 5 (2)",
      "wc_fuckitup05a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino1 = {
      "whitecustom@latino@bachata1",
      "pandora_fem",
      "~r~New ~b~Monaco Bachata 1 (F)",
      "wc_latino2",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino10 = {
      "whitecustom@latino@salsa1",
      "pandora_male",
      "~r~New ~b~Monaco Salsa 1 (M)",
      "wc_latino9",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino11 = {
      "whitecustom@latino@salsa2",
      "pandora_fem",
      "~r~New ~b~Monaco Salsa 2 (F)",
      "wc_latino12",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino12 = {
      "whitecustom@latino@salsa2",
      "pandora_male",
      "~r~New ~b~Monaco Salsa 2 (M)",
      "wc_latino11",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino13 = {
      "whitecustom@latino@salsa3",
      "pandora_fem",
      "~r~New ~b~Monaco Salsa 3 (F)",
      "wc_latino14",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino14 = {
      "whitecustom@latino@salsa3",
      "pandora_male",
      "~r~New ~b~Monaco Salsa 3 (M)",
      "wc_latino13",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino15 = {
      "whitecustom@latino@kompa1",
      "pandora_fem",
      "~r~New ~b~Monaco Kompa (F)",
      "wc_latino16",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino16 = {
      "whitecustom@latino@kompa1",
      "pandora_male",
      "~r~New ~b~Monaco Kompa (M)",
      "wc_latino15",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino2 = {
      "whitecustom@latino@bachata1",
      "pandora_male",
      "~r~New ~b~Monaco Bachata 1 (M)",
      "wc_latino1",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino3 = {
      "whitecustom@latino@bachata2",
      "pandora_fem",
      "~r~New ~b~Monaco Bachata 2 (F)",
      "wc_latino4",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino4 = {
      "whitecustom@latino@bachata2",
      "pandora_male",
      "~r~New ~b~Monaco Bachata 2 (M)",
      "wc_latino3",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino5 = {
      "whitecustom@latino@bachata3",
      "pandora_fem",
      "~r~New ~b~Monaco Bachata 3 (F)",
      "wc_latino6",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino6 = {
      "whitecustom@latino@bachata3",
      "pandora_male",
      "~r~New ~b~Monaco Bachata 3 (M)",
      "wc_latino5",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino7 = {
      "whitecustom@latino@bachata4",
      "pandora_fem",
      "~r~New ~b~Monaco Bachata 4 (F)",
      "wc_latino8",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_latino8 = {
      "whitecustom@latino@bachata4",
      "pandora_male",
      "~r~New ~b~Monaco Bachata 4 (M)",
      "wc_latino7",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_latino9 = {
      "whitecustom@latino@salsa1",
      "pandora_fem",
      "~r~New ~b~Monaco Salsa 1 (F)",
      "wc_latino10",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_1a = {
      "whitecustom@phoenix-1",
      "pandora",
      "~r~New ~b~Monaco Phoenix 1 (1)",
      "wc_phoenix_1b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_1b = {
      "whitecustom@phoenix-1",
      "pandora",
      "~r~New ~b~Monaco Phoenix 1 (2)",
      "wc_phoenix_1a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_phoenix_2a = {
      "whitecustom@phoenix-2",
      "pandora",
      "~r~New ~b~Monaco Phoenix 2 (1)",
      "wc_phoenix_2b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_2b = {
      "whitecustom@phoenix-2",
      "pandora",
      "~r~New ~b~Monaco Phoenix 2 (2)",
      "wc_phoenix_2a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_phoenix_3a = {
      "whitecustom@phoenix-3",
      "pandora",
      "~r~New ~b~Monaco Phoenix 3 (1)",
      "wc_phoenix_3b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_3b = {
      "whitecustom@phoenix-3",
      "pandora",
      "~r~New ~b~Monaco Phoenix 3 (2)",
      "wc_phoenix_3a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_phoenix_4a = {
      "whitecustom@phoenix-4",
      "pandora",
      "~r~New ~b~Monaco Phoenix 4 (1)",
      "wc_phoenix_4b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_4b = {
      "whitecustom@phoenix-4",
      "pandora",
      "~r~New ~b~Monaco Phoenix 4 (2)",
      "wc_phoenix_4a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_phoenix_5a = {
      "whitecustom@phoenix-5",
      "pandora",
      "~r~New ~b~Monaco Phoenix 5 (1)",
      "wc_phoenix_5b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_5b = {
      "whitecustom@phoenix-5",
      "pandora",
      "~r~New ~b~Monaco Phoenix 5 (2)",
      "wc_phoenix_5a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_phoenix_6a = {
      "whitecustom@phoenix-6",
      "pandora",
      "~r~New ~b~Monaco Phoenix 6 (1)",
      "wc_phoenix_6b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_6b = {
      "whitecustom@phoenix-6",
      "pandora",
      "~r~New ~b~Monaco Phoenix 6 (2)",
      "wc_phoenix_6a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_phoenix_7a = {
      "whitecustom@phoenix-7",
      "pandora",
      "~r~New ~b~Monaco Phoenix 7 (1)",
      "wc_phoenix_7b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 0.5,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_phoenix_7b = {
      "whitecustom@phoenix-7",
      "pandora",
      "~r~New ~b~Monaco Phoenix 7 (2)",
      "wc_phoenix_7a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_rhythm_01a = {
      "whitecustom@rhythm",
      "pandora01_f",
      "~r~New ~p~Monaco Rhythm 1 [F]",
      "wc_rhythm_01b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_rhythm_01b = {
      "whitecustom@rhythm",
      "pandora01_m",
      "~r~New ~p~Monaco Rhythm 1 [M]",
      "wc_rhythm_01a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_rhythm_02a = {
      "whitecustom@rhythm",
      "pandora02_f",
      "~r~New ~p~Monaco Rhythm 2 [F]",
      "wc_rhythm_02b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_rhythm_02b = {
      "whitecustom@rhythm",
      "pandora02_m",
      "~r~New ~p~Monaco Rhythm 2 [M]",
      "wc_rhythm_02a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_rhythm_04a = {
      "whitecustom@rhythm",
      "pandora04_f",
      "~r~New ~p~Monaco Rhythm 4 [F]",
      "wc_rhythm_04b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_rhythm_04b = {
      "whitecustom@rhythm",
      "pandora04_m",
      "~r~New ~p~Monaco Rhythm 4 [M]",
      "wc_rhythm_04a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_sexy_1a = {
      "whitecustom@sexy-1",
      "pandora",
      "~r~New ~p~Monaco Sexy 1 [M]",
      "wc_sexy_1b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 1.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_sexy_1b = {
      "whitecustom@sexy-1",
      "pandora",
      "~r~New ~p~Monaco Sexy 1 [F]",
      "wc_sexy_1a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_sexy_2a = {
      "whitecustom@sexy-2",
      "pandora",
      "~r~New ~p~Monaco Sexy 2 [M]",
      "wc_sexy_2b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 1.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_sexy_2b = {
      "whitecustom@sexy-2",
      "pandora",
      "~r~New ~p~Monaco Sexy 2 [F]",
      "wc_sexy_2a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_sexy_3a = {
      "whitecustom@sexy-3",
      "pandora",
      "~r~New ~p~Monaco Sexy 3 [M]",
      "wc_sexy_3b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 1.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_sexy_3b = {
      "whitecustom@sexy-3",
      "pandora",
      "~r~New ~p~Monaco Sexy 3 [F]",
      "wc_sexy_3a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_sexy_4a = {
      "whitecustom@sexy-4",
      "pandora",
      "~r~New ~p~Monaco Sexy 4 [M]",
      "wc_sexy_4b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 1.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_sexy_4b = {
      "whitecustom@sexy-4",
      "pandora",
      "~r~New ~p~Monaco Sexy 4 [F]",
      "wc_sexy_4a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_sexy_5a = {
      "whitecustom@sexy-5",
      "pandora",
      "~r~New ~p~Monaco Sexy 5 [M]",
      "wc_sexy_5b",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.8,
        xRot = 0.0,
        yPos = 1.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_sexy_5b = {
      "whitecustom@sexy-5",
      "pandora",
      "~r~New ~p~Monaco Sexy 5 [F]",
      "wc_sexy_5a",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_tiktok_1as = {
      "whitecustom@tiktok",
      "pandora01",
      "~r~New ~b~Monaco Tisto 1 (1)",
      "wc_tiktok_1bs",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 1.2,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_tiktok_1bs = {
      "whitecustom@tiktok",
      "pandora01",
      "~r~New ~b~Monaco Tisto 1 (2)",
      "wc_tiktok_1as",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_tiktok_2as = {
      "whitecustom@tiktok",
      "pandora02",
      "~r~New ~b~Monaco Tisto 2 (1)",
      "wc_tiktok_2bs",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 1.2,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_tiktok_2bs = {
      "whitecustom@tiktok",
      "pandora02",
      "~r~New ~b~Monaco Tisto 2 (2)",
      "wc_tiktok_2as",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_tiktok_3as = {
      "whitecustom@tiktok",
      "pandora03a",
      "~r~New ~b~Monaco Tisto 3 (F)",
      "wc_tiktok_3bs",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 0.0,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_tiktok_3bs = {
      "whitecustom@tiktok",
      "pandora03b",
      "~r~New ~b~Monaco Tisto 3 (M)",
      "wc_tiktok_3as",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_tiktok_4as = {
      "whitecustom@tiktok",
      "pandora04",
      "~r~New ~b~Monaco Tisto 4 (1)",
      "wc_tiktok_4bs",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 1.2,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_tiktok_4bs = {
      "whitecustom@tiktok",
      "pandora04",
      "~r~New ~b~Monaco Tisto 4 (2)",
      "wc_tiktok_4as",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
    wc_tiktok_5as = {
      "whitecustom@tiktok",
      "pandora05",
      "~r~New ~b~Monaco Tisto 5 (1)",
      "wc_tiktok_5bs",
      AnimationOptions = {
        Attachto = true,
        EmoteLoop = true,
        EmoteMoving = false,
        xPos = 1.2,
        xRot = 0.0,
        yPos = 0.0,
        yRot = 0.0,
        zPos = 0.0,
        zRot = 0.0,
      },
    },
    wc_tiktok_5bs = {
      "whitecustom@tiktok",
      "pandora05",
      "~r~New ~b~Monaco Tisto 5 (2)",
      "wc_tiktok_5as",
      AnimationOptions = {
        EmoteLoop = true,
        EmoteMoving = false,
      },
    },
  },
  Walks = {
  },
}

-- Carrega os emotes adicionais deste arquivo dentro da tabela global `RP`.
function LoadAddonEmotes()
  local prefixByCategory = {
    Shared = "🤼 ",
    AnimalEmotes = "🐶 ",
    PropEmotes = "📦 ",
  }

  for categoryName, categoryTable in pairs(AddonEmotes) do
    if RP[categoryName] then
      local prefix = prefixByCategory[categoryName]

      for emoteName, emoteData in pairs(categoryTable) do
        if prefix then
          emoteData[3] = prefix .. emoteData[3]
        end

        RP[categoryName][emoteName] = emoteData
      end
    end
  end

  AddonEmotes = nil
end

